[package]
name = "guests"
version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }

[build-dependencies]
risc0-build = { workspace = true }
rustc_version = { workspace = true }

[package.metadata.risc0]
methods = ["stateless-client"]
