[package]
name = "zeth-guests-reth-optimism"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies.risc0-zkvm]
version = "1.1.3"
default-features = false
features = ["std"]

[dependencies.risc0-zkvm-platform]
version = "1.1.3"
features = ["sys-getenv"]

[dependencies.zeth-core]
path = "../../crates/core"
default-features = false

[dependencies.zeth-core-optimism]
path = "../../crates/core-optimism"
default-features = false

[dependencies]
anyhow = { version = "1.0.86", default-features = false }
c-kzg = { version = "=1.0.3", features = ["risc0-ffi"] }
lazy_static = "1.5.0"

reth-optimism-chainspec = { git = "https://github.com/risc0/reth", branch = "p1.1.0_zstd", default-features = false, features = ["std"] }

[patch.crates-io]
crypto-bigint = { git = "https://github.com/risc0/RustCrypto-crypto-bigint", tag = "v0.5.5-risczero.0" }
k256 = { git = "https://github.com/risc0/RustCrypto-elliptic-curves", tag = "k256/v0.13.3-risczero.0" }
sha2 = { git = "https://github.com/risc0/RustCrypto-hashes", tag = "sha2-v0.10.6-risczero.0" }
c-kzg = { git = "https://github.com/risc0/c-kzg-4844.git", branch = "p1.0.3" }
