name: risczero toolchain install
description: Install risczero toolchain

inputs:
  version:
    description: 'Version of the RISC Zero to install'
    required: true
    type: string
  toolchain-version:
    description: 'Version of the RISC Zero toolchains to install'
    required: false
    default: ''
    type: string

runs:
  using: composite
  steps:
    - name: install rust
      uses: risc0/risc0/.github/actions/rustup@release-${{ inputs.version }}

    - name: Install rzup
      env:
        ENV_PATH: test
      shell: bash
      run: |
        curl -L https://risczero.com/install | bash
        echo "$HOME/.risc0/bin" >> $GITHUB_PATH

    - name: rzup install rust
      shell: bash
      run: rzup install rust ${{ inputs.toolchain-version }}

    - name: test risczero
      shell: bash
      run: cargo risczero --version
