name: risczero toolchain install
description: Install risczero toolchain

runs:
  using: composite
  steps:
    - name: install rust
      uses: risc0/risc0/.github/actions/rustup@release1.3

    - name: Install rzup
      env:
        ENV_PATH: test
      shell: bash
      run: |
        curl -L https://risczero.com/install | bash
        echo "$HOME/.risc0/bin" >> $GITHUB_PATH

    - name: rzup install rust
      shell: bash
      run: rzup install rust r0.1.83.0

    - name: test risczero
      shell: bash
      run: cargo risczero --version
