name: risczero toolchain install
description: Install risczero toolchain

inputs:
  risc0_rust_ver:
    default: "1.81.0"

runs:
  using: composite
  steps:
    - name: install rust
      uses: risc0/risc0/.github/actions/rustup@release-1.3

    - name: Install rzup
      env:
        ENV_PATH: test
      shell: bash
      run: |
        curl -L https://risczero.com/install | bash
        echo "$HOME/.risc0/bin" >> $GITHUB_PATH

    - name: rzup install rust
      shell: bash
      run: rzup install rust ${{ inputs.risc0_rust_ver }}
