[package]
name = "zeth"
version = "0.1.0"
edition = "2021"

[dependencies.risc0-zkvm]
workspace = true
features = ["std"]

[dependencies.zeth-core]
workspace = true

[dependencies.zeth-guests]
workspace = true

[dependencies.zeth-preflight]
workspace = true

[dependencies]
alloy.workspace = true
anyhow.workspace = true
bincode.workspace = true
clap.workspace = true
env_logger.workspace = true
log.workspace = true

reth-chainspec.workspace = true
reth-primitives.workspace = true
reth-revm.workspace = true

serde.workspace = true
tokio.workspace = true
tracing.workspace = true

[features]
metal = ["risc0-zkvm/metal"]
cuda = ["risc0-zkvm/cuda"]
disable-dev-mode = ["risc0-zkvm/disable-dev-mode"]
