[package]
name = "zeth-benchmark"
version = "0.1.0"
edition = "2021"

[dependencies.zeth]
workspace = true

[dependencies.zeth-core]
workspace = true

[dependencies]
alloy.workspace = true
alloy-chains.workspace = true
anyhow.workspace = true
clap.workspace = true
env_logger.workspace = true
tracing.workspace = true
log = "0.4.22"

[features]
metal = ["zeth/metal"]
cuda = ["zeth/cuda"]
disable-dev-mode = ["zeth/disable-dev-mode"]
