[package]
name = "zeth-benchmark"
version = "0.1.0"
edition = "2021"

[dependencies.zeth]
workspace = true

[dependencies.zeth-core]
workspace = true

[dependencies]
alloy.workspace = true
alloy-chains.workspace = true
clap.workspace = true
env_logger.workspace = true
tracing.workspace = true

[features]
disable-dev-mode = ["zeth/disable-dev-mode"]
cuda = ["zeth/cuda"]
metal = ["zeth/metal"]
prove = ["zeth/prove"]
