[package]
name = "zeth-testeth"
version = "0.1.0"
edition = "2021"

[features]
cuda = []
ef-tests = []
metal = []

[dependencies]
alloy = { workspace = true, features = ["full","serde","rlp"] }
alloy-trie = "0.6"
anyhow = { workspace = true }
nybbles = "0.2"
reth-chainspec  = { workspace = true }
reth-primitives = { workspace = true }
reth-revm = { workspace = true }
reth-storage-errors = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
zeth-core = { workspace = true }
zeth-core-ethereum = { workspace = true }
zeth-preflight ={ workspace = true }
zeth-preflight-ethereum ={ workspace = true }

[dev-dependencies]
env_logger = "0.11"
log = "0.4"
rstest = "0.23"

[package.metadata.risc0]
methods = ["testguest"]
