name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: risc0/risc0/.github/actions/rustup@release-0.16
    - uses: risc0/risc0/.github/actions/sccache@release-0.16
    - name: Cargo test
      run: cargo test --workspace
