name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# this is needed to gain access via OIDC to the S3 bucket for caching
permissions:
  id-token: write
  contents: read

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  RISC0_VERSION: "1.0.5"
  RISC0_TOOLCHAIN_VERSION: v2024-04-22.0

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: risc0/risc0/.github/actions/rustup@v1.0.5
    - uses: risc0/risc0/.github/actions/sccache@v1.0.5
    - uses: risc0/cargo-install@v1
      with:
        crate: cargo-binstall
    - run: cargo binstall -y --force cargo-risczero@$RISC0_VERSION
    - run: cargo risczero install --version $RISC0_TOOLCHAIN_VERSION
    - run: cargo test --workspace --all-targets -F ef-tests,debug-guest-build

  clippy:
    name: clippy
    runs-on: [self-hosted, prod, "${{ matrix.os }}"]
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: Linux
            feature: default
          - os: Linux
            feature: cuda
          - os: macOS
            feature: default
          - os: macOS
            feature: metal
    env:
      FEATURE: ${{ matrix.feature }}
      RISC0_SKIP_BUILD: 1
      RISC0_SKIP_BUILD_KERNELS: 1
    steps:
      - uses: actions/checkout@v4
      - if: matrix.feature == 'cuda'
        uses: risc0/risc0/.github/actions/cuda@v1.0.5
      - uses: risc0/risc0/.github/actions/rustup@v1.0.5
      - uses: risc0/risc0/.github/actions/sccache@v1.0.5
      - uses: risc0/clippy-action@main
        with:
          reporter: 'github-pr-check'
          fail_on_error: true
          clippy_flags: -F $FEATURE --workspace --all-targets -- -Dwarnings

  fmt:
    name: fmt
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - uses: risc0/risc0/.github/actions/rustup@v1.0.5
    - run: cargo fmt --all --check
