name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# this is needed to gain access via OIDC to the S3 bucket for caching
permissions:
  id-token: write
  contents: read

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  RISC0_VERSION: "^0.21"
  RISC0_TOOLCHAIN_VERSION: v2024-02-08.1

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: risc0/risc0/.github/actions/rustup@release-0.21
    - uses: risc0/risc0/.github/actions/sccache@release-0.21
    - uses: risc0/cargo-install@v1
      with:
        crate: cargo-binstall
    - run: cargo binstall -y --force cargo-risczero@$RISC0_VERSION
    - run: cargo risczero install --version $RISC0_TOOLCHAIN_VERSION
    - run: cargo test --workspace --all-targets -F ef-tests,debug-guest-build

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
    - uses: risc0/risc0/.github/actions/rustup@release-0.21
    - uses: risc0/risc0/.github/actions/sccache@release-0.21
    - uses: risc0/clippy-action@main
      with:
        reporter: 'github-pr-check'
        fail_on_error: true
        clippy_flags: --workspace --all-targets -- -Dwarnings

  fmt:
    name: fmt
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - uses: risc0/risc0/.github/actions/rustup@release-0.21
    - run: cargo fmt --all --check
